### ISSUE TITLE
BTS module

### ISSUE THREAD

**Issue by clelouch** [zwbx/BTS-Net#2]
![image](https://user-images.githubusercontent.com/33519394/132606503-bd9fd508-5b81-4174-a233-5c437d8aae40.png)
![image](https://user-images.githubusercontent.com/33519394/132606510-0aada375-4cf6-4559-a3bc-09b9329cd6b7.png)
The code is inconsistent with the figure. In the code, the img_att is first computed. The result is then utilized to calculate the depth_att. However, in the figure, the img_att and depth_att are calculated seperately.

**Comment by zwbx** [comment]
Thanks for your comment, we have checked and confirm it as our mistake.
According to our experience, it will not influence the whole performance though, for the main promotion comes from bi-direcition interaction strategy.
