### ISSUE TITLE
cross spatial attention and self channel attention

### ISSUE THREAD

**Issue by clelouch** [zwbx/BTS-Net#5]
Thanks for your code and paper.
I am curious that why you use the cross spatial attention and self channel attention. Have you tried to use cross channel attention to further enable mutual refinement?

**Comment by zwbx** [comment]
Our main idea starts from exchanging features of RGB and depth in the encoder stage. As for the specific implementation, the way we proposed is just one of the ways that might work.

We did not try cross-channel attention for we think it's hard to explain the mechanism though it might work. 
Another work can demonstrate this idea. That is "Full-Duplex Strategy for Video Object Segmentation", where cross-channel attention seems to work well.

**Comment by clelouch** [comment]
Thanks for your reply.
