### ISSUE TITLE
About released trained model

### ISSUE THREAD

**Issue by big-feather** [zwbx/BTS-Net#7]
Could you please explain the reason for such high performance ([0.0154 mae], [0.9716 max-fmeasure], [0.9632 S-measure_alpha05]) on the NJU2K dataset using the published trained model, while the other datasets are basically the same as the paper?

**Comment by zwbx** [comment]
please check the test dataset for it has different split version. 发自我的 iPhone在 2023年1月4日，10:26，big-feather ***@***.***> 写道：﻿
Could you please explain the reason for such high performance ([0.0154 mae], [0.9716 max-fmeasure], [0.9632 S-measure_alpha05]) on the NJU2K dataset using the published trained model, while the other datasets are basically the same as the paper?

**Comment by big-feather** [comment]
thanks
